config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'notifications/index'
  get '/profile/:id', to: 'users#show'
  get '/', to: redirect('/home')
  get '/home', to: 'tweets#index'
  devise_for :users
  resources :users, only: %i[show]
  resources :tweets do
    resources :comments
  end
  resources :followers, only: %i[create show]
  resources :likes, only: %i[create]
  resources :messages
  resources :notifications
  root 'tweets#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
  validates_presence_of :text
end

app/models/follower.rb
# frozen_string_literal: true

class Follower < ApplicationRecord
  belongs_to :user
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/tweet.rb
# frozen_string_literal: true

class Tweet < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes
  validates :text, presence: true
  has_one_attached :cover_picture
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :tweets
  has_many :likes
  has_many :followers
  attr_writer :login

  validate :validate_username

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates_presence_of(:name)
  validates_presence_of(:username)
  validates_uniqueness_of(:username)
  validates_presence_of(:password)
  validates_presence_of(:password_confirmation)

  def login
    @login || username || email
  end

  def validate_username
    errors.add(:username, :invalid) if User.where(email: username).exists?
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(['lower(username) = :value OR lower(email) = :value',
                                    { value: login.downcase }]).first
    elsif conditions.key?(:username) || conditions.key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  def create
    tweet = Tweet.find(params[:tweet_id])
    user = current_user.id
    comment = Comment.new(comment_params)
    comment.user_id = user
    comment.tweet_id = tweet.id

    if comment.save
      flash[:notice] = 'Comment added successfully.'
      redirect_to tweet_path(tweet)
    else
      flash[:error] = "The comment couldn't be saved."
      redirect_to tweet_path(tweet)
    end
  end

  def comment_params
    params.require(:comment).permit(:text, :tweet_id)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @tweets = Tweet.all.order('created_at')
    @tweet = Tweet.new
    @users = User.all
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  def create
    tweet = Tweet.find(params[:id])
    like = Like.find_by(user_id: current_user.id, tweet_id: params[:id])

    if like
      like.destroy
      redirect_to tweet_path(tweet)
    else
      like = tweet.likes.build(user_id: current_user.id)

      if like.save
        redirect_to tweet_path(tweet)
      else
        flash[:error] = "Error Couldn't like the tweet."
        redirect_to tweet_path(tweet)
      end
    end
  end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
end

app/controllers/tweets_controller.rb
# frozen_string_literal: true

class TweetsController < ApplicationController
  def index
    @new_tweet = Tweet.new
    @users = User.all
    followers = current_user.followers
    @tweets = Tweet.all.order('created_at DESC')
    @tweets = @tweets.filter do |tweet|
      followers.any? do |follower|
        follower.follower_id == tweet.user_id
      end || tweet.user_id == current_user.id
    end
  end

  def new
    @tweet = Tweet.new
  end

  def create
    user = User.find(current_user.id)
    @tweet = user.tweets.build(tweet_params)
    if @tweet.save
      flash[:notice] = 'Tweet added successfully.'
      redirect_to home_path
    else
      flash[:error] = "Error The Tweet couldn't be saved"
      redirect_to home_path
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comment = Comment.new
  end

  def tweet_params
    params.require(:tweet).permit(:text, :cover_picture)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @user_names = @user.name.split(' ')
    @following = Follower.where(follower_id: @user.id).count
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/followers_helper.rb
# frozen_string_literal: true

module FollowersHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
end

app/helpers/messages_helper.rb
# frozen_string_literal: true

module MessagesHelper
end

app/helpers/notifications_helper.rb
# frozen_string_literal: true

module NotificationsHelper
end

app/helpers/registrations_helper.rb
# frozen_string_literal: true

module RegistrationsHelper
end

app/helpers/tweets_helper.rb
# frozen_string_literal: true

module TweetsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/home/_navbar.html.erb
<nav class="main-navbar-container">
    <div class="navbar-main-container">
        <div class="navbar-logo-container">
            <i class="bi bi-twitter"></i>
        </div>
        <ul class="navbar-links-main-container">
            <li>
                <%= link_to root_path do %>
                <div class="navlink-item-container">
                    <div class="navlink-icon">
                        <i class="bi bi-house"></i>
                    </div>
                    <div class="navlink-text">
                        Home
                    </div>
                </div>
                <% end %>
            </li>
            <li>
                <%= link_to root_path do %>
                <div class="navlink-item-container">
                    <div class="navlink-icon">
                        <i class="bi bi-hash"></i>
                    </div>
                    <div class="navlink-text">
                        Explore
                    </div>
                </div>
                <% end %>
            </li>
            <li>
                <%= link_to notifications_path do %>
                <div class="navlink-item-container">
                    <div class="navlink-icon">
                        <i class="bi bi-bell"></i>
                    </div>
                    <div class="navlink-text">
                        Notifications
                    </div>
                </div>
                <% end %>
            </li>
            <li>
                <%= link_to messages_path do %>
                <div class="navlink-item-container">
                    <div class="navlink-icon">
                        <i class="bi bi-envelope"></i>
                    </div>
                    <div class="navlink-text">
                        Messages
                    </div>
                </div>
                <% end %>
            </li>

            <li>
                <%= link_to user_path(current_user) do %>
                <div class="navlink-item-container">
                    <div class="navlink-icon">
                        <i class="bi bi-person"></i>
                    </div>
                    <div class="navlink-text">
                        Profile
                    </div>
                </div>
                <% end %>
            </li>
            <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                <div class="navlink-item-container">
                    <div class="navlink-icon">
                        <i class="bi bi-box-arrow-right"></i>
                    </div>
                    <div class="navlink-text">
                        Logout
                    </div>
                </div>
                <% end %>
            </li>
            <li>
                <%= link_to new_tweet_path do %>
                <div class="tweet-btn">
                    Tweet
                </div>
                <% end %>
            </li>
        </ul>
    </div>
    <div class="profile-details">
        <div class="profile-image-container">
            <img src="https://pbs.twimg.com/profile_images/1387328259424194560/M2y5iSup_normal.jpg" alt="profile">
        </div>
        <div class="profile-names-area">
            <h2><%= current_user.name %></h2>
            <span>@<%= current_user.username %></span>
        </div>

        <div class="profile-options">
            <%
=begin%>
            <i class="bi bi-three-dots"></i>
            <%
=end%>
        </div>
    </div>
</nav>

app/views/home/index.html.erb
<section class="navigation-wrapper">
    <%= render "home/navbar" %>
</section>
<main class="main-app-wrapper">
    <div class="yield-app-main-wrapper">
        <section class="home-main-container">
            <header class="home-header-container">
                <div class="image-text-wrapper">
                    <div class="header-text">
                        Home
                    </div>
                </div>
                <div class="header-top-tweets-icon">
                    <svg viewBox="0 0 24 24" aria-hidden="true" class="r-13gxpu9 r-4qtqp9 r-yyyyoo r-1q142lx r-50lct3 r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-1srniue">
                        <g>
                            <path d="M22.772 10.506l-5.618-2.192-2.16-6.5c-.102-.307-.39-.514-.712-.514s-.61.207-.712.513l-2.16 6.5-5.62 2.192c-.287.112-.477.39-.477.7s.19.585.478.698l5.62 2.192 2.16 6.5c.102.306.39.513.712.513s.61-.207.712-.513l2.16-6.5 5.62-2.192c.287-.112.477-.39.477-.7s-.19-.585-.478-.697zm-6.49 2.32c-.208.08-.37.25-.44.46l-1.56 4.695-1.56-4.693c-.07-.21-.23-.38-.438-.462l-4.155-1.62 4.154-1.622c.208-.08.37-.25.44-.462l1.56-4.693 1.56 4.694c.07.212.23.382.438.463l4.155 1.62-4.155 1.622zM6.663 3.812h-1.88V2.05c0-.414-.337-.75-.75-.75s-.75.336-.75.75v1.762H1.5c-.414 0-.75.336-.75.75s.336.75.75.75h1.782v1.762c0 .414.336.75.75.75s.75-.336.75-.75V5.312h1.88c.415 0 .75-.336.75-.75s-.335-.75-.75-.75zm2.535 15.622h-1.1v-1.016c0-.414-.335-.75-.75-.75s-.75.336-.75.75v1.016H5.57c-.414 0-.75.336-.75.75s.336.75.75.75H6.6v1.016c0 .414.335.75.75.75s.75-.336.75-.75v-1.016h1.098c.414 0 .75-.336.75-.75s-.336-.75-.75-.75z"></path>
                        </g>
                    </svg>
                </div>
            </header>
            <div class="home-content-area">
                <div class="home-new-tweet-input-area">
                    <%= render "shared/tweet_input", tweet: @tweet %>
                </div>
                <div class="tweets-main-container-area">
                    <% @tweets.each do |tweet|%>
                    <%= render "shared/tweet", images: tweet.cover_image ? [tweet.image] : [] ,tweet: tweet, user_names: @user_names %>
                    <%end%>
                </div>
        </section>
    </div>
    <aside class="search-main-wrapper">
    </aside>
</main>

<div class="overlay">
</div>
<%= javascript_pack_tag 'input' %>

app/views/messages/_message.html.erb
<div class="message-main-container <%= current %>">

    <div class="message-content-user">
        <div class="user-image">
            <div class="image">
                <%= image_tag("https://pbs.twimg.com/profile_images/1387328259424194560/M2y5iSup_normal.jpg") %>
            </div>
        </div>
        <div class="message-text">
            <div class="text">
                Hello Barack , we are in final phases, did you fill the form at our page?
            </div>
        </div>
    </div>
    <div class="message-history">
        <span>Mar 28, 2021, 8:56 AM</span>
    </div>

</div>

app/views/messages/_room.html.erb
<a class="chat-contact-item-container">
    <div class="contact-image">
        <div class="image">
            <%= image_tag("https://pbs.twimg.com/profile_images/1387328259424194560/M2y5iSup_normal.jpg")%>
        </div>
    </div>
    <div class="contact-details">
        <div class="name-date">
            <div class="names">
                <h2>
                    Canalbox Rwanda
                </h2>
                <h4>
                    @CanalBoxR
                </h4>
            </div>

        </div>
        <div class="last-message">
            I think it doesn't pass because it is...
        </div>
    </div>
    <div class="last-message-history">
        <span> May 19</span>
    </div>
</a>

app/views/messages/index.html.erb
<section class="navigation-wrapper">
    <%= render "home/navbar" %>
</section>
<main class="main-app-wrapper">
    <div class="yield-app-main-wrapper messages">
        <section class="home-main-container">
            <header class="home-header-container">
                <div class="image-text-wrapper">
                    <div class="header-text">

                        <div class="profile-user-info">
                            <h2> Messages
                            </h2>
                        </div>
                    </div>
                </div>
                <div class="header-top-tweets-icon">
                    <svg viewBox="0 0 24 24" aria-hidden="true" class="r-13gxpu9 r-4qtqp9 r-yyyyoo r-1q142lx r-50lct3 r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-1srniue">
                        <g>
                            <path d="M23.25 3.25h-2.425V.825c0-.414-.336-.75-.75-.75s-.75.336-.75.75V3.25H16.9c-.414 0-.75.336-.75.75s.336.75.75.75h2.425v2.425c0 .414.336.75.75.75s.75-.336.75-.75V4.75h2.425c.414 0 .75-.336.75-.75s-.336-.75-.75-.75zm-3.175 6.876c-.414 0-.75.336-.75.75v8.078c0 .414-.337.75-.75.75H4.095c-.412 0-.75-.336-.75-.75V8.298l6.778 4.518c.368.246.79.37 1.213.37.422 0 .844-.124 1.212-.37l4.53-3.013c.336-.223.428-.676.204-1.012-.223-.332-.675-.425-1.012-.2l-4.53 3.014c-.246.162-.563.163-.808 0l-7.586-5.06V5.5c0-.414.337-.75.75-.75h9.094c.414 0 .75-.336.75-.75s-.336-.75-.75-.75H4.096c-1.24 0-2.25 1.01-2.25 2.25v13.455c0 1.24 1.01 2.25 2.25 2.25h14.48c1.24 0 2.25-1.01 2.25-2.25v-8.078c0-.415-.337-.75-.75-.75z"></path>
                        </g>
                    </svg>
                </div>
            </header>
            <div class="contacts-main-container">
                <div class="header">
                    <div class="contact-search-container">
                        <i class="bi bi-search"></i>
                        <input type="text" placeholder="Search for people" />
                    </div>
                </div>

                <div class="contacts-wrapper">
                    <% [0,2,3,4,5].each do |item| %>
                    <%= render "room" %>
                    <%end%>
                </div>
            </div>
        </section>
        <section class="home-main-container chat-room-main-container">
            <header class="home-header-container">
                <div class="image-text-wrapper">
                    <div class="header-text">
                        <div class="profile-user-info">
                            <div class="user-image">
                                <div class="image">
                                    <%= image_tag("https://pbs.twimg.com/profile_images/1387328259424194560/M2y5iSup_normal.jpg") %>
                                </div>
                            </div>
                            <div class="user-names">
                                <h2>Barack Mukelenga</h2>
                                <h4>@BarackMukelenga</h4>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="header-top-tweets-icon">
                    <svg viewBox="0 0 24 24" aria-hidden="true" class="r-13gxpu9 r-4qtqp9 r-yyyyoo r-1q142lx r-50lct3 r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-1srniue">
                        <g>
                            <path d="M12 18.042c-.553 0-1-.447-1-1v-5.5c0-.553.447-1 1-1s1 .447 1 1v5.5c0 .553-.447 1-1 1z"></path>
                            <circle cx="12" cy="8.042" r="1.25"></circle>
                            <path d="M12 22.75C6.072 22.75 1.25 17.928 1.25 12S6.072 1.25 12 1.25 22.75 6.072 22.75 12 17.928 22.75 12 22.75zm0-20C6.9 2.75 2.75 6.9 2.75 12S6.9 21.25 12 21.25s9.25-4.15 9.25-9.25S17.1 2.75 12 2.75z"></path>
                        </g>
                    </svg>
                </div>
            </header>
            <div class="chat-messages-container-area">

                <div class="header">
                    <div class="header-content">
                        <div class="user">
                            <h2>Canalbox Rwanda</h2>
                            <h4>@CanalboxR</h4>
                        </div>
                        <div class="bio">
                            Unlimited very high-speed Internet connection offer for households and the corporate community in Kigali
                            Customer support: 8600
                        </div>
                        <div class="followers-info">
                            <div class="following">
                                <p><strong>46</strong> Following</p>
                            </div>
                            <div class="following">
                                <p><strong>2.645</strong> Followers</p>
                            </div>
                        </div>
                        <div class="joined-at">
                            <i class="bi bi-calendar3"></i> <strong>Joined March 2020</strong>
                        </div>
                    </div>

                </div>
                <div class="messages">
                    <% [0, 2,3,4,5,6,7].each do |item| %>
                    <%= render "message", current: "" %>
                    <%= render "message", current: "current" %>
                    <%end%>
                </div>
            </div>
            <footer class="chat-room-footer">
                <div class="send-message-btn">
                    <div class="btn">
                        <svg viewBox="0 0 24 24" aria-hidden="true" class="r-13gxpu9 r-4qtqp9 r-yyyyoo r-1q142lx r-50lct3 r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-1srniue">
                            <g>
                                <path d="M19.75 2H4.25C3.01 2 2 3.01 2 4.25v15.5C2 20.99 3.01 22 4.25 22h15.5c1.24 0 2.25-1.01 2.25-2.25V4.25C22 3.01 20.99 2 19.75 2zM4.25 3.5h15.5c.413 0 .75.337.75.75v9.676l-3.858-3.858c-.14-.14-.33-.22-.53-.22h-.003c-.2 0-.393.08-.532.224l-4.317 4.384-1.813-1.806c-.14-.14-.33-.22-.53-.22-.193-.03-.395.08-.535.227L3.5 17.642V4.25c0-.413.337-.75.75-.75zm-.744 16.28l5.418-5.534 6.282 6.254H4.25c-.402 0-.727-.322-.744-.72zm16.244.72h-2.42l-5.007-4.987 3.792-3.85 4.385 4.384v3.703c0 .413-.337.75-.75.75z"></path>
                                <circle cx="8.868" cy="8.309" r="1.542"></circle>
                            </g>
                        </svg>
                    </div>
                </div>
                <div class="chat-input-container">
                    <div data-controller="auto-grow-textarea" class="reach-text-editor-main-container">
                        <%= form_with do |form| %>
                        <%= form.rich_text_area :content, placeholder: "Start a new message" %>
                        <%end%>
                    </div>
                    <div class="send-message-btn emojie">
                        <div class="btn">
                            <svg viewBox="0 0 24 24" aria-hidden="true" class="r-13gxpu9 r-4qtqp9 r-yyyyoo r-1q142lx r-50lct3 r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-1srniue">
                                <g>
                                    <path d="M12 22.75C6.072 22.75 1.25 17.928 1.25 12S6.072 1.25 12 1.25 22.75 6.072 22.75 12 17.928 22.75 12 22.75zm0-20C6.9 2.75 2.75 6.9 2.75 12S6.9 21.25 12 21.25s9.25-4.15 9.25-9.25S17.1 2.75 12 2.75z"></path>
                                    <path d="M12 17.115c-1.892 0-3.633-.95-4.656-2.544-.224-.348-.123-.81.226-1.035.348-.226.812-.124 1.036.226.747 1.162 2.016 1.855 3.395 1.855s2.648-.693 3.396-1.854c.224-.35.688-.45 1.036-.225.35.224.45.688.226 1.036-1.025 1.594-2.766 2.545-4.658 2.545z"></path>
                                    <circle cx="14.738" cy="9.458" r="1.478"></circle>
                                    <circle cx="9.262" cy="9.458" r="1.478"></circle>
                                </g>
                            </svg>
                        </div>
                    </div>

                </div>
                <div class="send-message-btn">
                    <div class="btn">
                        <svg viewBox="0 0 24 24" aria-hidden="true" class="r-13gxpu9 r-4qtqp9 r-yyyyoo r-1q142lx r-50lct3 r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-1srniue">
                            <g>
                                <path d="M21.13 11.358L3.614 2.108c-.29-.152-.64-.102-.873.126-.23.226-.293.577-.15.868l4.362 8.92-4.362 8.92c-.143.292-.08.643.15.868.145.14.333.212.523.212.12 0 .24-.028.35-.087l17.517-9.25c.245-.13.4-.386.4-.664s-.155-.532-.4-.662zM4.948 4.51l12.804 6.762H8.255l-3.307-6.76zm3.307 8.26h9.498L4.948 19.535l3.307-6.763z"></path>
                            </g>
                        </svg>
                    </div>
                </div>
            </footer>
        </section>
    </div>
</main>

<div class="overlay">
</div>

<%= javascript_pack_tag 'input' %>