config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'notifications/index'
  get '/profile/:id', to: 'users#show'
  get '/', to: redirect('/home')
  get '/home', to: 'tweets#index'
  devise_for :users
  resources :users, only: %i[show]
  resources :tweets do
    resources :comments
  end
  resources :followers, only: %i[create show]
  resources :likes, only: %i[create]
  resources :messages
  resources :notifications
  root 'tweets#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
  validates_presence_of :text
end

app/models/follower.rb
# frozen_string_literal: true

class Follower < ApplicationRecord
  belongs_to :user
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/tweet.rb
# frozen_string_literal: true

class Tweet < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes
  validates :text, presence: true
  has_one_attached :cover_picture
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :tweets
  has_many :likes
  has_many :followers
  attr_writer :login

  validate :validate_username

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates_presence_of(:name)
  validates_presence_of(:username)
  validates_uniqueness_of(:username)
  validates_presence_of(:password)
  validates_presence_of(:password_confirmation)

  def login
    @login || username || email
  end

  def validate_username
    errors.add(:username, :invalid) if User.where(email: username).exists?
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(['lower(username) = :value OR lower(email) = :value',
                                    { value: login.downcase }]).first
    elsif conditions.key?(:username) || conditions.key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  def create
    tweet = Tweet.find(params[:tweet_id])
    user = current_user.id
    comment = Comment.new(comment_params)
    comment.user_id = user
    comment.tweet_id = tweet.id

    if comment.save
      flash[:notice] = 'Comment added successfully.'
      redirect_to tweet_path(tweet)
    else
      flash[:error] = "The comment couldn't be saved."
      redirect_to tweet_path(tweet)
    end
  end

  def comment_params
    params.require(:comment).permit(:text, :tweet_id)
  end
end

app/controllers/followers_controller.rb
# frozen_string_literal: true

class FollowersController < ApplicationController
  def show
    @user = User.find(params[:id])
    if @user
      @followers = @user.followers.all.order('created_at DESC')
      @followers = @followers.filter { |follower| follower.follower_id != current_user.id }
      @following = Follower.where(follower_id: @user.id)
      @user_names = @user.name.split(' ')
      @users = User.all
      @followers_all = Follower.all
      @followers_you_know = @followers.filter do |follower|
        @followers_all.any? do |f|
          f.user_id == follower.follower_id && f.follower_id == current_user.id
        end
        # && follower.follower_id != current_user.id
      end
      p @followers_you_know
    else
      redirect_to root_path
    end
  end

  def create
    user = User.find(params[:id])
    if user
      follower = Follower.where(follower_id: current_user.id, user_id: user.id)
      if follower[0]
        follower[0].destroy
        redirect_to user_path(user)
      else
        follower = user.followers.new
        follower.follower_id = current_user.id
        if follower.save
          redirect_to user_path(user)
        else
          redirect_to user_path(user)
        end
      end
    end
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @tweets = Tweet.all.order('created_at')
    @tweet = Tweet.new
    @users = User.all
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  def create
    tweet = Tweet.find(params[:id])
    like = Like.find_by(user_id: current_user.id, tweet_id: params[:id])

    if like
      like.destroy
      redirect_to tweet_path(tweet)
    else
      like = tweet.likes.build(user_id: current_user.id)

      if like.save
        redirect_to tweet_path(tweet)
      else
        flash[:error] = "Error Couldn't like the tweet."
        redirect_to tweet_path(tweet)
      end
    end
  end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
end

app/controllers/tweets_controller.rb
# frozen_string_literal: true

class TweetsController < ApplicationController
  def index
    @new_tweet = Tweet.new
    @users = User.all
    followers = current_user.followers
    @tweets = Tweet.all.order('created_at DESC')
    @tweets = @tweets.filter do |tweet|
      followers.any? do |follower|
        follower.follower_id == tweet.user_id
      end || tweet.user_id == current_user.id
    end
  end

  def new
    @tweet = Tweet.new
  end

  def create
    user = User.find(current_user.id)
    @tweet = user.tweets.build(tweet_params)
    if @tweet.save
      flash[:notice] = 'Tweet added successfully.'
      redirect_to home_path
    else
      flash[:error] = "Error The Tweet couldn't be saved"
      redirect_to home_path
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comment = Comment.new
  end

  def tweet_params
    params.require(:tweet).permit(:text, :cover_picture)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @user_names = @user.name.split(' ')
    @following = Follower.where(follower_id: @user.id).count
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/followers_helper.rb
# frozen_string_literal: true

module FollowersHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
end

app/helpers/messages_helper.rb
# frozen_string_literal: true

module MessagesHelper
end

app/helpers/notifications_helper.rb
# frozen_string_literal: true

module NotificationsHelper
end

app/helpers/registrations_helper.rb
# frozen_string_literal: true

module RegistrationsHelper
end

app/helpers/tweets_helper.rb
# frozen_string_literal: true

module TweetsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/followers/_follower.html.erb
<div class="follower-main-container-item">
    <div class="follower-item-image-wrapper">
        <%= link_to user_path(user_follower) do %>
        <div class="image">
            <%= image_tag("https://pbs.twimg.com/profile_images/1387328259424194560/M2y5iSup_normal.jpg") %>
        </div>
        <% end %>
    </div>
    <div class="follower-details">
        <div class="header">
            <div class="follower-name">
                <%= link_to user_path(user_follower) do %>
                <h2> <%= user_follower.name %> </h2>
                <% end %>
                <h4>
                    @<%= user_follower.name %>
                </h4>
            </div>
            <% if followers.filter {|follower| follower.user_id == user_follower.id}.any? {|follower| follower.follower_id == current_user.id } %>
            <div class="follow-btn-whapper following">
                <%= link_to followers_path(:id => user_follower.id), method: :post do %>
                <div class="btn">
                    Following
                </div>
                <% end %>
            </div>
            <%else%>
            <div class="follow-btn-whapper follow">
                <%= link_to followers_path(:id => user_follower.id), method: :post do %>
                <div class="btn">
                    Follow
                </div>
                <% end %>
            </div>
            <%end%>
        </div>
        <div class="bio-container">
            <div class="text">
                <%= user_follower.about %>
            </div>
        </div>
    </div>
</div>

app/views/tweets/index.html.erb
<section class="navigation-wrapper">
    <%= render "home/navbar" %>
</section>
<main class="main-app-wrapper">
    <div class="yield-app-main-wrapper">
        <section class="home-main-container">
            <header class="home-header-container">
                <div class="image-text-wrapper">
                    <div class="header-text">
                        Home
                    </div>
                </div>
                <div class="header-top-tweets-icon">
                    <svg viewBox="0 0 24 24" aria-hidden="true" class="r-13gxpu9 r-4qtqp9 r-yyyyoo r-1q142lx r-50lct3 r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-1srniue">
                        <g>
                            <path d="M22.772 10.506l-5.618-2.192-2.16-6.5c-.102-.307-.39-.514-.712-.514s-.61.207-.712.513l-2.16 6.5-5.62 2.192c-.287.112-.477.39-.477.7s.19.585.478.698l5.62 2.192 2.16 6.5c.102.306.39.513.712.513s.61-.207.712-.513l2.16-6.5 5.62-2.192c.287-.112.477-.39.477-.7s-.19-.585-.478-.697zm-6.49 2.32c-.208.08-.37.25-.44.46l-1.56 4.695-1.56-4.693c-.07-.21-.23-.38-.438-.462l-4.155-1.62 4.154-1.622c.208-.08.37-.25.44-.462l1.56-4.693 1.56 4.694c.07.212.23.382.438.463l4.155 1.62-4.155 1.622zM6.663 3.812h-1.88V2.05c0-.414-.337-.75-.75-.75s-.75.336-.75.75v1.762H1.5c-.414 0-.75.336-.75.75s.336.75.75.75h1.782v1.762c0 .414.336.75.75.75s.75-.336.75-.75V5.312h1.88c.415 0 .75-.336.75-.75s-.335-.75-.75-.75zm2.535 15.622h-1.1v-1.016c0-.414-.335-.75-.75-.75s-.75.336-.75.75v1.016H5.57c-.414 0-.75.336-.75.75s.336.75.75.75H6.6v1.016c0 .414.335.75.75.75s.75-.336.75-.75v-1.016h1.098c.414 0 .75-.336.75-.75s-.336-.75-.75-.75z"></path>
                        </g>
                    </svg>
                </div>
            </header>
            <div class="home-content-area">
                <div class="home-new-tweet-input-area">
                    <%= render "shared/tweet_input", tweet: @new_tweet %>
                </div>
                <div class="tweets-main-container-area">
                    <% @tweets.each do |tweet|%>
                    <% p tweet.cover_picture%>
                    <%= render "shared/tweet", images:  tweet.cover_picture.attached? ? [tweet.cover_picture] : [],tweet: tweet %>
                    <%end%>
                </div>
        </section>
    </div>
    <aside class="search-main-wrapper">
    </aside>
</main>

<div class="overlay">
</div>
<%= javascript_pack_tag 'input' %>

app/views/tweets/new.html.erb
<section class="navigation-wrapper">
    <%= render "home/navbar" %>
</section>
<main class="main-app-wrapper">
    <div class="yield-app-main-wrapper">
        <section class="home-main-container">
            <header class="home-header-container">
                <div class="image-text-wrapper">
                    <div class="header-text">
                        <%= link_to root_path do %>
                        <div class="header-back-arrow">
                            <i class="bi bi-arrow-left"></i>
                        </div>
                        <%end %>
                        Tweet
                    </div>
                </div>
                <div class="header-top-tweets-icon">
                    <svg viewBox="0 0 24 24" aria-hidden="true" class="r-13gxpu9 r-4qtqp9 r-yyyyoo r-1q142lx r-50lct3 r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-1srniue">
                        <g>
                            <path d="M22.772 10.506l-5.618-2.192-2.16-6.5c-.102-.307-.39-.514-.712-.514s-.61.207-.712.513l-2.16 6.5-5.62 2.192c-.287.112-.477.39-.477.7s.19.585.478.698l5.62 2.192 2.16 6.5c.102.306.39.513.712.513s.61-.207.712-.513l2.16-6.5 5.62-2.192c.287-.112.477-.39.477-.7s-.19-.585-.478-.697zm-6.49 2.32c-.208.08-.37.25-.44.46l-1.56 4.695-1.56-4.693c-.07-.21-.23-.38-.438-.462l-4.155-1.62 4.154-1.622c.208-.08.37-.25.44-.462l1.56-4.693 1.56 4.694c.07.212.23.382.438.463l4.155 1.62-4.155 1.622zM6.663 3.812h-1.88V2.05c0-.414-.337-.75-.75-.75s-.75.336-.75.75v1.762H1.5c-.414 0-.75.336-.75.75s.336.75.75.75h1.782v1.762c0 .414.336.75.75.75s.75-.336.75-.75V5.312h1.88c.415 0 .75-.336.75-.75s-.335-.75-.75-.75zm2.535 15.622h-1.1v-1.016c0-.414-.335-.75-.75-.75s-.75.336-.75.75v1.016H5.57c-.414 0-.75.336-.75.75s.336.75.75.75H6.6v1.016c0 .414.335.75.75.75s.75-.336.75-.75v-1.016h1.098c.414 0 .75-.336.75-.75s-.336-.75-.75-.75z"></path>
                        </g>
                    </svg>
                </div>
            </header>
            <div class="home-content-area">
                <div class="home-new-tweet-input-area">
                    <%= render "shared/tweet_input", tweet: @tweet %>
                </div>
        </section>
    </div>
    <aside class="search-main-wrapper">
    </aside>
</main>

<div class="overlay">
</div>
<%= javascript_pack_tag 'input' %>

app/views/tweets/show.html.erb
<section class="navigation-wrapper">
    <%= render "home/navbar" %>
</section>
<main class="main-app-wrapper">
    <div class="yield-app-main-wrapper">
        <section class="home-main-container">
            <header class="home-header-container">
                <div class="image-text-wrapper">
                    <div class="header-text">
                        <%= link_to :back do %>
                        <div class="header-back-arrow">
                            <i class="bi bi-arrow-left"></i>
                        </div>
                        <%end %>
                        Tweet
                    </div>
                </div>
                <div class="header-top-tweets-icon">
                    <svg viewBox="0 0 24 24" aria-hidden="true" class="r-13gxpu9 r-4qtqp9 r-yyyyoo r-1q142lx r-50lct3 r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-1srniue">
                        <g>
                            <path d="M22.772 10.506l-5.618-2.192-2.16-6.5c-.102-.307-.39-.514-.712-.514s-.61.207-.712.513l-2.16 6.5-5.62 2.192c-.287.112-.477.39-.477.7s.19.585.478.698l5.62 2.192 2.16 6.5c.102.306.39.513.712.513s.61-.207.712-.513l2.16-6.5 5.62-2.192c.287-.112.477-.39.477-.7s-.19-.585-.478-.697zm-6.49 2.32c-.208.08-.37.25-.44.46l-1.56 4.695-1.56-4.693c-.07-.21-.23-.38-.438-.462l-4.155-1.62 4.154-1.622c.208-.08.37-.25.44-.462l1.56-4.693 1.56 4.694c.07.212.23.382.438.463l4.155 1.62-4.155 1.622zM6.663 3.812h-1.88V2.05c0-.414-.337-.75-.75-.75s-.75.336-.75.75v1.762H1.5c-.414 0-.75.336-.75.75s.336.75.75.75h1.782v1.762c0 .414.336.75.75.75s.75-.336.75-.75V5.312h1.88c.415 0 .75-.336.75-.75s-.335-.75-.75-.75zm2.535 15.622h-1.1v-1.016c0-.414-.335-.75-.75-.75s-.75.336-.75.75v1.016H5.57c-.414 0-.75.336-.75.75s.336.75.75.75H6.6v1.016c0 .414.335.75.75.75s.75-.336.75-.75v-1.016h1.098c.414 0 .75-.336.75-.75s-.336-.75-.75-.75z"></path>
                        </g>
                    </svg>
                </div>
            </header>
            <div class="tweet-item-main-container details">
                <div class="tweet-item-wrapper">
                    <div class="tweet-user-profile-container">
                        <%= link_to user_path(@tweet.user) do %>
                        <div class="tweet-user">
                            <div class="image">
                                <img src="https://pbs.twimg.com/profile_images/1387328259424194560/M2y5iSup_normal.jpg" alt="prodile">
                            </div>
                        </div>
                        <%end %>
                    </div>
                    <div class="tweet-detail-main-container">
                        <div class="tweet-header-main-container">

                            <div class="user-name-history">
                                <div class="user-name">
                                    <%= link_to user_path(@tweet.user)  do %>
                                    <h3><%= @tweet.user.name.split(" ")[0] %> <% if @tweet.user.name.split(" ")[1] %>
                                        <%= @tweet.user.name.split(" ")[1]%>
                                        <%end %>
                                    </h3>
                                    <%end %>
                                    <span>@<%= @tweet.user.username %><span>
                                </div>

                                <div class="tweet-history timestring">
                                    <%= @tweet.created_at %>
                                </div>
                            </div>
                            <div class="tweet-more-details">
                                <div>
                                    <i class="bi bi-three-dots"></i>
                                </div>
                            </div>
                        </div>
                        <div class="tweet-body">
                            <div class="tweet-text"> <%= @tweet.text%> </div>
                            <% if(@tweet.cover_picture.attached?) %>
                            <div class="tweet-images-container">
                                <div class="tweet-image-item">
                                    <%= image_tag(@tweet.cover_picture)%>
                                </div>
                            </div>
                            <%end%>
                        </div>
                        <div class="tweet-footer">
                            <div class="footer-item">
                                <i class="bi bi-chat"></i>
                                <span>
                                    <%= @tweet.comments.count %>
                                </span>
                            </div>
                            <div class="footer-item">
                                <svg viewBox="0 0 24 24" aria-hidden="true" class="r-4qtqp9 r-yyyyoo r-1xvli5t r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-1hdv0qi">
                                    <g>
                                        <path d="M23.77 15.67c-.292-.293-.767-.293-1.06 0l-2.22 2.22V7.65c0-2.068-1.683-3.75-3.75-3.75h-5.85c-.414 0-.75.336-.75.75s.336.75.75.75h5.85c1.24 0 2.25 1.01 2.25 2.25v10.24l-2.22-2.22c-.293-.293-.768-.293-1.06 0s-.294.768 0 1.06l3.5 3.5c.145.147.337.22.53.22s.383-.072.53-.22l3.5-3.5c.294-.292.294-.767 0-1.06zm-10.66 3.28H7.26c-1.24 0-2.25-1.01-2.25-2.25V6.46l2.22 2.22c.148.147.34.22.532.22s.384-.073.53-.22c.293-.293.293-.768 0-1.06l-3.5-3.5c-.293-.294-.768-.294-1.06 0l-3.5 3.5c-.294.292-.294.767 0 1.06s.767.293 1.06 0l2.22-2.22V16.7c0 2.068 1.683 3.75 3.75 3.75h5.85c.414 0 .75-.336.75-.75s-.337-.75-.75-.75z"></path>
                                    </g>
                                </svg>
                                <span>
                                    83
                                </span>
                            </div>
                            <%= link_to likes_path(:id => @tweet.id), method: :post do%>
                            <% if @tweet.likes.any? {|tweet| tweet.user_id == current_user.id} %>
                            <div class="footer-item liked">
                                <i class="bi bi-heart-fill"></i>
                                <span>
                                    <%= @tweet.likes.count%>
                                </span>
                            </div>
                            <% else %>
                            <div class="footer-item liked">
                                <i class="bi bi-heart"></i>
                                <span>
                                    <%= @tweet.likes.count%>
                                </span>
                            </div>
                            <% end %>
                            <%end %>
                            <div class="footer-item">
                                <i class="bi bi-upload"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tweet-details-comment-input">
                <div class="new-tweet-container">
                    <div class="image-wrapper">
                        <div class="image-container">
                            <img src="https://pbs.twimg.com/profile_images/1387328259424194560/M2y5iSup_normal.jpg" alt="profile" />
                        </div>
                    </div>
                    <div class="input-details-main-wrapper">
                        <%= form_with(model: @comment, url: tweet_comments_path(@tweet)) do |form| %>
                        <div class="input-text-area-wrapper">
                            <%= form.text_area :text, placeholder:"Enter your comment",class:"new-tweet-home-input-form" %>
                        </div>
                        <div class="form-controls">
                            <div class="tweet-form-media">
                                <div class="tweet-media-items">
                                    <div class="tweet-media-items">
                                        <i class="bi bi-image"></i>
                                    </div>
                                    <div class="tweet-media-items">
                                        <i class="bi bi-emoji-smile"></i>
                                    </div>
                                </div>
                                <%= form.submit "Comment", class:"tweet-form-submit-btn" %>
                            </div>
                        </div>
                        <% end %>
                    </div>
                </div>
            </div>
            <div class="tweet-details-comments-container">
                <% @tweet.comments.order("created_at DESC").each do |comment| %>
                <%= render "shared/comment", comment: comment, images:[] %>
                <%end %>
            </div>
        </section>
    </div>
    <aside class="search-main-wrapper">
    </aside>
</main>

<div class="overlay">
</div>
<%= javascript_pack_tag 'input' %>

app/views/users/show.html.erb
<section class="navigation-wrapper">
    <%= render "home/navbar" %>
</section>
<main class="main-app-wrapper">
    <div class="yield-app-main-wrapper">
        <section class="home-main-container">
            <header class="home-header-container">
                <div class="image-text-wrapper">
                    <div class="header-text">
                        <%= link_to :back do %>
                        <div class="header-back-arrow">
                            <i class="bi bi-arrow-left"></i>
                        </div>
                        <%end %>
                        <div class="profile-user-info">
                            <h2> <%= @user_names[0].capitalize %>
                                <% if @user_names[1] %>
                                <%= @user_names[1].capitalize %>
                                <%end %>
                            </h2>
                            <span class="profile-header-tweets-count">
                                <%= @user.tweets.count %> <% if @user.tweets.count == 1%>
                                Tweet
                                <%else %>
                                Tweets
                                <%end %>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="header-top-tweets-icon">
                    <svg viewBox="0 0 24 24" aria-hidden="true" class="r-13gxpu9 r-4qtqp9 r-yyyyoo r-1q142lx r-50lct3 r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-1srniue">
                        <g>
                            <path d="M22.772 10.506l-5.618-2.192-2.16-6.5c-.102-.307-.39-.514-.712-.514s-.61.207-.712.513l-2.16 6.5-5.62 2.192c-.287.112-.477.39-.477.7s.19.585.478.698l5.62 2.192 2.16 6.5c.102.306.39.513.712.513s.61-.207.712-.513l2.16-6.5 5.62-2.192c.287-.112.477-.39.477-.7s-.19-.585-.478-.697zm-6.49 2.32c-.208.08-.37.25-.44.46l-1.56 4.695-1.56-4.693c-.07-.21-.23-.38-.438-.462l-4.155-1.62 4.154-1.622c.208-.08.37-.25.44-.462l1.56-4.693 1.56 4.694c.07.212.23.382.438.463l4.155 1.62-4.155 1.622zM6.663 3.812h-1.88V2.05c0-.414-.337-.75-.75-.75s-.75.336-.75.75v1.762H1.5c-.414 0-.75.336-.75.75s.336.75.75.75h1.782v1.762c0 .414.336.75.75.75s.75-.336.75-.75V5.312h1.88c.415 0 .75-.336.75-.75s-.335-.75-.75-.75zm2.535 15.622h-1.1v-1.016c0-.414-.335-.75-.75-.75s-.75.336-.75.75v1.016H5.57c-.414 0-.75.336-.75.75s.336.75.75.75H6.6v1.016c0 .414.335.75.75.75s.75-.336.75-.75v-1.016h1.098c.414 0 .75-.336.75-.75s-.336-.75-.75-.75z"></path>
                        </g>
                    </svg>
                </div>
            </header>
            <div class="home-content-area">
                <div class="profile-main-header-wrapper">
                    <div class="profile-background-image">
                        <%= image_tag("https://pbs.twimg.com/profile_banners/986945306657894400/1619599809/600x200")%>
                        <div class="user-profile-image">
                            <div class="user-image">
                                <%= image_tag("https://pbs.twimg.com/profile_images/1387328259424194560/M2y5iSup_200x200.jpg")%>
                            </div>
                        </div>
                    </div>
                    <div class="profile-user-more-details">
                        <% if(current_user.id == @user.id)%>
                        <%= link_to edit_user_registration_path do %>
                        <div class="follow-btn-whapper">
                            <div>
                            </div>
                            <div class="btn">
                                Edit Profile
                            </div>
                        </div>
                        <%end%>
                        <%elsif @user.followers.any? {|f| f.follower_id == current_user.id} %>
                        <div class="follow-btn-whapper following">
                            <div>
                            </div>
                            <%= link_to followers_path(:id => @user.id), method: :post do %>
                            <div class="btn">
                                Following
                            </div>
                            <% end %>
                        </div>
                        <%else%>
                        <div class="follow-btn-whapper follow">
                            <div>
                            </div>
                            <%= link_to followers_path(:id => @user.id), method: :post do %>
                            <div class="btn">
                                Follow
                            </div>
                            <% end %>

                        </div>
                        <%end%>
                        <div class="user-names">
                            <h2> <%= @user_names[0].capitalize %>
                                <% if @user_names[1] %>
                                <%= @user_names[1].capitalize %>
                                <%end %>
                            </h2>
                            <h4>@<%= @user_names[0].capitalize %><% if @user_names[1] %><%= @user_names[1].capitalize %>
                                <%end %></h4>
                        </div>

                        <div class="user-bio-container">
                            <%= @user.about %>
                        </div>

                        <div class="location-and-joined-details">
                            <%if @user.location %>
                            <div class="user-location">
                                <i class="bi bi-geo-alt"></i> <%= @user.location %>
                            </div>
                            <%end %>
                            <%if @user.website %>
                            <div class="user-location">
                                <i class="bi bi-link-45deg"></i> <%= link_to @user.website, URI::HTTP.build({:host => @user.website}).to_s, :target => "_blank" %>
                            </div>
                            <%end %>
                            <div class="user-joined-at">
                                <i class="bi bi-calendar3"></i> Joined <%= timeago_tag @user.created_at, limit: 1.minute.ago %>
                            </div>
                        </div>

                        <div class="following-information">
                            <%= link_to follower_path(:id => @user.id) do %>
                            <div class="following">
                                <strong>
                                    <%= @following %>
                                </strong>
                                Following
                            </div>
                            <%end%>
                            <%= link_to follower_path(:id => @user.id) do %>
                            <div class="followers">
                                <strong>
                                    <%= @user.followers.count%>
                                </strong>
                                Followers
                            </div>
                            <%end%>
                        </div>
                    </div>
                </div>
                <div class="profile-tab-navigation">
                    <ul>
                        <li>
                            <a class="active">
                                Tweet
                            </a>
                        </li>
                        <li>
                            <a>
                                Tweets & replies
                            </a>
                        </li>
                        <li>
                            <a>
                                Media
                            </a>
                        </li>
                        <li>
                            <a>
                                Likes
                            </a>
                        </li>

                    </ul>
                </div>
            </div>

            <div class="profile-tweets-media-likes-main-container">
                <div class="profile-user-tweets-container">
                    <% @user.tweets.each do |tweet| %>
                    <%= render "shared/tweet", tweet:tweet, images: tweet.cover_picture.attached? ? [tweet.cover_picture]: [] %>
                    <% end %>
                </div>
            </div>
        </section>
    </div>
    <aside class="search-main-wrapper">
    </aside>
</main>

<div class="overlay">
</div>